export const data = [
  {
    closeUrl: '',
    slug: 'BTC-1',
    icon: '/placeholder/btc.png',
    name: 'Bitcoin',
    symbol: 'BTC',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'utility',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
  {
    closeUrl: '',
    slug: 'ETH-1',
    icon: '/placeholder/eth.png',
    name: 'Ethereum',
    symbol: 'ETH',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'liquid',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
  {
    closeUrl: '',
    slug: 'BTC-2',
    icon: '/placeholder/btc.png',
    name: 'Bitcoin',
    symbol: 'BTC',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'utility',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
  {
    closeUrl: '',
    slug: 'ETH-2',
    icon: '/placeholder/eth.png',
    name: 'Ethereum',
    symbol: 'ETH',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'liquid',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
  {
    closeUrl: '',
    slug: 'BTC-3',
    icon: '/placeholder/btc.png',
    name: 'Bitcoin',
    symbol: 'BTC',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'utility',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
  {
    closeUrl: '',
    slug: 'ETH-3',
    icon: '/placeholder/eth.png',
    name: 'Ethereum',
    symbol: 'ETH',
    value: 5.25791,
    usdEqual: 335887.76,
    status: 'liquid',
    chartData: [
      { month: 'January', value: 186000, date: '2024-01-15' },
      { month: 'February', value: 305000, date: '2024-02-10' },
      { month: 'March', value: 237000, date: '2024-03-05' },
      { month: 'April', value: 73000, date: '2024-08-01' },
      { month: 'May', value: 209000, date: '2024-09-12' },
      { month: 'June', value: 214000, date: '2024-10-10' },
    ],
    transactions: [
      {
        id: '1',
        title: 'Transaction 1',
        description: 'Description 1',
        amount: 100,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 1', variant: 'outline' as const }],
        author: { name: 'John', surname: 'Doe' },
        viewCount: 10,
        commentCount: 2,
      },
      {
        id: '2',
        title: 'Transaction 2',
        description: 'Description 2',
        amount: 200,
        withUsdSymbol: true,
        badges: [{ label: 'Tag 2', variant: 'outline' as const }],
        author: { name: 'Jane', surname: 'Doe' },
        viewCount: 15,
        commentCount: 5,
      },
    ],
  },
];
