import { createGlobPatternsForDependencies } from '@nx/react/tailwind';
import { join } from 'node:path';
import TailwindAnimate from 'tailwindcss-animate';

import type { Config } from 'tailwindcss';

export function buildConfig(appDir: string): Config {
  return {
    darkMode: ['class'],
    safelist: ['dark', 'light'],
    content: [
      join(
        appDir,
        '{src,pages,components,app}/**/*!(*.stories|*.spec).{ts,tsx,html}'
      ),
      '../../packages/ui/src/**/*!(*.stories|*.spec).{ts,tsx,html}',
      '../../packages/epics/src/**/*!(*.stories|*.spec).{ts,tsx,html}',
      ...createGlobPatternsForDependencies(appDir),
    ],
    theme: {
      extend: {
        colors: {
          border: 'hsl(var(--border))',
          input: 'hsl(var(--input))',
          ring: 'hsl(var(--ring))',
          accent: {
            DEFAULT: 'hsl(var(--accent))',
            foreground: 'hsl(var(--accent-foreground))',
            1: 'hsl(var(--accent-1))',
            2: 'hsl(var(--accent-2))',
            3: 'hsl(var(--accent-3))',
            4: 'hsl(var(--accent-4))',
            5: 'hsl(var(--accent-5))',
            6: 'hsl(var(--accent-6))',
            7: 'hsl(var(--accent-7))',
            8: 'hsl(var(--accent-8))',
            9: 'hsl(var(--accent-9))',
            10: 'hsl(var(--accent-10))',
            11: 'hsl(var(--accent-11))',
            12: 'hsl(var(--accent-12))',
          },
          background: {
            DEFAULT: 'hsl(var(--background))',
            1: 'hsl(var(--background-1))',
            2: 'hsl(var(--background-2))',
            3: 'hsl(var(--background-3))',
            4: 'hsl(var(--background-4))',
            5: 'hsl(var(--background-5))',
            6: 'hsl(var(--background-6))',
            7: 'hsl(var(--background-7))',
            8: 'hsl(var(--background-8))',
            9: 'hsl(var(--background-9))',
            10: 'hsl(var(--background-10))',
            11: 'hsl(var(--background-11))',
            12: 'hsl(var(--background-12))',
          },
          error: {
            DEFAULT: 'hsl(var(--error))',
            1: 'hsl(var(--error-1))',
            2: 'hsl(var(--error-2))',
            3: 'hsl(var(--error-3))',
            4: 'hsl(var(--error-4))',
            5: 'hsl(var(--error-5))',
            6: 'hsl(var(--error-6))',
            7: 'hsl(var(--error-7))',
            8: 'hsl(var(--error-8))',
            9: 'hsl(var(--error-9))',
            10: 'hsl(var(--error-10))',
            11: 'hsl(var(--error-11))',
            12: 'hsl(var(--error-12))',
          },
          info: {
            DEFAULT: 'hsl(var(--info))',
            1: 'hsl(var(--info-1))',
            2: 'hsl(var(--info-2))',
            3: 'hsl(var(--info-3))',
            4: 'hsl(var(--info-4))',
            5: 'hsl(var(--info-5))',
            6: 'hsl(var(--info-6))',
            7: 'hsl(var(--info-7))',
            8: 'hsl(var(--info-8))',
            9: 'hsl(var(--info-9))',
            10: 'hsl(var(--info-10))',
            11: 'hsl(var(--info-11))',
            12: 'hsl(var(--info-12))',
          },
          success: {
            DEFAULT: 'hsl(var(--success))',
            1: 'hsl(var(--success-1))',
            2: 'hsl(var(--success-2))',
            3: 'hsl(var(--success-3))',
            4: 'hsl(var(--success-4))',
            5: 'hsl(var(--success-5))',
            6: 'hsl(var(--success-6))',
            7: 'hsl(var(--success-7))',
            8: 'hsl(var(--success-8))',
            9: 'hsl(var(--success-9))',
            10: 'hsl(var(--success-10))',
            11: 'hsl(var(--success-11))',
            12: 'hsl(var(--success-12))',
          },
          neutral: {
            DEFAULT: 'hsl(var(--neutral))',
            1: 'hsl(var(--neutral-1))',
            2: 'hsl(var(--neutral-2))',
            3: 'hsl(var(--neutral-3))',
            4: 'hsl(var(--neutral-4))',
            5: 'hsl(var(--neutral-5))',
            6: 'hsl(var(--neutral-6))',
            7: 'hsl(var(--neutral-7))',
            8: 'hsl(var(--neutral-8))',
            9: 'hsl(var(--neutral-9))',
            10: 'hsl(var(--neutral-10))',
            11: 'hsl(var(--neutral-11))',
            12: 'hsl(var(--neutral-12))',
          },
          warning: {
            DEFAULT: 'hsl(var(--warning))',
            1: 'hsl(var(--warning-1))',
            2: 'hsl(var(--warning-2))',
            3: 'hsl(var(--warning-3))',
            4: 'hsl(var(--warning-4))',
            5: 'hsl(var(--warning-5))',
            6: 'hsl(var(--warning-6))',
            7: 'hsl(var(--warning-7))',
            8: 'hsl(var(--warning-8))',
            9: 'hsl(var(--warning-9))',
            10: 'hsl(var(--warning-10))',
            11: 'hsl(var(--warning-11))',
            12: 'hsl(var(--warning-12))',
          },
          foreground: 'hsl(var(--foreground))',
          primary: {
            DEFAULT: 'hsl(var(--primary))',
            foreground: 'hsl(var(--primary-foreground))',
          },
          secondary: {
            DEFAULT: 'hsl(var(--secondary))',
            foreground: 'hsl(var(--secondary-foreground))',
          },
          destructive: {
            DEFAULT: 'hsl(var(--destructive))',
            foreground: 'hsl(var(--destructive-foreground))',
          },
          muted: {
            DEFAULT: 'hsl(var(--muted))',
            foreground: 'hsl(var(--muted-foreground))',
          },
          popover: {
            DEFAULT: 'hsl(var(--popover))',
            foreground: 'hsl(var(--popover-foreground))',
          },
          card: {
            DEFAULT: 'hsl(var(--card))',
            foreground: 'hsl(var(--card-foreground))',
          },
          action: {
            DEFAULT: 'rgb(62, 99, 221)',
            foreground: 'rgb(32, 58, 119)',
          },
          'action-light': {
            DEFAULT: 'hsl(var(--action-light))',
            foreground: 'hsl(var(--action-light))',
          },
        },
        borderRadius: {
          lg: `var(--radius)`,
          md: `calc(var(--radius) - 2px)`,
          sm: 'calc(var(--radius) - 4px)',
        },
        fontSize: {
          '1': '14px',
          '2': '16px',
          '3': '18px',
          '4': '20px',
          '5': '24px',
          '6': '30px',
          '7': '36px',
          '8': '48px',
          '9': '60px',
        },
        keyframes: {
          'accordion-down': {
            from: { height: '0' },
            to: { height: 'var(--radix-accordion-content-height)' },
          },
          'accordion-up': {
            from: { height: 'var(--radix-accordion-content-height)' },
            to: { height: '0' },
          },
        },
        animation: {
          'accordion-down': 'accordion-down 0.2s ease-out',
          'accordion-up': 'accordion-up 0.2s ease-out',
        },
      },
    },
    plugins: [TailwindAnimate],
  };
}
